version: '3.8'

services:
  go-app:
    build: ./go
    ports:
      - "8080:8080"
    depends_on:
      - db

  nextjs:
    build: ./nextjs
    ports:
      - "3000:3000"
    depends_on:
      - db

  wordpress:
    build: ./wordpress
    ports:
      - "8000:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: username
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: exampledb
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: database_name
      MYSQL_USER: username
      MYSQL_PASSWORD: password

