
name: Nextjs CI for lint and Print

on:
  push:
    branches: [ "main" ]

jobs:
  NextjsLint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code 
      uses: actions/checkout@v4

    - name: Set up node
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    - name: Install dependencies
      run: cd nextjs && npm install

    - name: Nextjs Linting
      run: cd nextjs && npm run lint
   
    - name: Running nextjs app 
      run: cd nextjs && npm run dev

