
name: Nextjs CI for lint and Print

on:
  push:
    branches: [ "main" ]

jobs:
  NextjsLint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code 
      uses: actions/checkout@v4

    - name: Set up node
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    - name: Install dependencies
      run: cd nextjs && npm install

    - name: Nextjs Linting
      run: cd nextjs && npm run lint
   
    - name: Installing pm2 globally
      run: npm install -g pm2@latest
      
    - name: building next app
      run: cd nextjs && npm run build
      
    - name: starting pm2 instance and sleep
      run: |
        cd nextjs && pm2 start npm --name "my-app" -- start
        sleep 30
        pm2 logs --nostream

  deploy:
      runs-on: ubuntu-latest
      needs: NextjsLint
  
      steps:
        - name: Deploy to main/Staging
          run: echo "Deploying Nexrjs app to main/staging..."
