name: wordpress CI 

on:
  push:
    branches: [ "main", "feature/*"]

jobs:
  NextjsLint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code 
      uses: actions/checkout@v4

    - name: Set up node
      uses: actions/setup-php@v4
      with:
        php-version: '8'
        
    - name: Install Php CS
      run: cd wordpress && composer global require "squizlabs/php_codesniffer=*"
      
    - name: Run PHP
      run: cd wordpress && php ./hello.php

        
    
