name: wordpress CI 

on:
  push:
    branches: [ "main", "feature/*"]

jobs:
  PHP:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout code 
      uses: actions/checkout@v4

    - name: Set up php
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
        
    - name: Install Php CS
      run: |
        cd wordpress && composer global require "squizlabs/php_codesniffer=*"
        cat ~/.composer/composer.json
        echo "true" | composer config --global --no-plugins allow-plugins.johnpbloch/wordpress-core-installer
        composer global require johnpbloch/wordpress-core
        composer global require johnpbloch/wordpress
        cat ~/.composer/composer.json
        ls -lrth ~/.composer/
        #composer self-update && composer global update
        #composer g require --dev automattic/vipwpcs -W
      
    - name: phpcs standards and version
      run: phpcs -i && phpcs --version
      
    - name: Run Hello PHP
      run: cd wordpress && php ./hello.php

        
    
