name: wordpress CI 

on:
  push:
    branches: [ "main", "feature/*"]

jobs:
  PHP:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout code 
      uses: actions/checkout@v4

    - name: Set up php
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        
    - name: Install Php CS
      run: |
        composer global require "squizlabs/php_codesniffer=*"
        phpcs -i
        #git clone -b main https://github.com/WordPress/WordPress-Coding-Standards.git wpcs
        #cd wordpress && phpcs --config-set installed_paths ~/.composer/vendor/wp-coding-standards/
        composer global require "wp-coding-standards/wpcs"
        phpcs --config-set installed_paths ~/.composer/vendor/wp-coding-standards/wpcs
        phpcs -i
        cat /home/runner/.composer/vendor/squizlabs/php_codesniffer/CodeSniffer.conf
        # phpcs --standard=WordPress ./wordpress/hello.php
        which phpcs
        pwd
        ls -lrath ~
      
    - name: phpcs standards and version
      run: phpcs -i && phpcs --version
      
    - name: Run Hello PHP
      run: cd wordpress && php ./hello.php

        
    
